name: windows

on: [push]
    
jobs:
  build:
    name: build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: initialize
      run: cmake -G "Visual Studio 17 2022" .
    - name: compile
      run: cmake --build . 
    - name: test
      run: |
            cd tests
            ctest .
